services:
    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing
        hostname: syncthing
        ports:
            - 22000:22000/tcp
            - 22000:22000/udp
            - 21027:21027/udp
        volumes:
            - /var/syncthing:/var/syncthing
            - syncthing_data:/var/data
        restart: unless-stopped
        networks:
            - proxy_network
        healthcheck:
            test: curl -fkLsS -m 2 localhost:8384/rest/noauth/health | grep -o --color=never OK || exit 1
            interval: 1m
            timeout: 10s
            retries: 3

    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        volumes:
            - vaultwarden_data:/data/
        restart: unless-stopped
        environment:
            ROCKET_WEB_VAULT_PREFIX: /vaultwarden
        networks:
            - proxy_network

    gitea:
        image: docker.io/gitea/gitea:nightly
        container_name: gitea
        environment:
            USER_UID: ${PUID}
            USER_GID: ${PGID}
            GITEA__database__DB_TYPE: mysql
            GITEA__database__HOST: database:3306
            GITEA__database__NAME: ${GITEA_DATABASE_NAME}
            GITEA__database__USER: ${GITEA_DATABASE_USER}
            GITEA__database__PASSWD: ${GITEA_DATABASE_PASSWORD}
            GITEA__mailer__ENABLED: true
            GITEA__mailer__PROTOCOL: smtps
        restart: unless-stopped
        networks:
            - proxy_network
        volumes:
            - gitea_data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - .env

    homeassistant:
        image: ghcr.io/home-assistant/home-assistant:stable
        container_name: homeassistant
        privileged: true
        restart: unless-stopped
        volumes:
            - homeassistant_data:/config
            - /run/dbus:/run/dbus:ro
            - /etc/localtime:/etc/localtime:ro
        network_mode: host
        env_file:
            - .env

    gotify:
        image: gotify/server
        container_name: gotify
        volumes:
            - gotify_data:/app/data
        networks:
            - proxy_network
        env_file:
            - .env

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    syncthing_data:
        name: syncthing_data
        driver: local
    vaultwarden_data:
        name: vaultwarden_data
        driver: local
    gitea_data:
        name: gitea_data
        driver: local
    homeassistant_data:
        name: homeassistant_data
        driver: local
    gotify_data:
        name: gotify_data
        driver: local
