services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - "80:3000"
        volumes:
            - ./config/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped

    portainer:
        image: portainer/portainer-ce:lts
        container_name: portainer
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - uptime-kuma:/app/data

volumes:
    portainer_data:
        name: portainer_data
        driver: local
    uptime-kuma:
        name: uptime-kuma
        driver: local
