services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - "80:3000"
        volumes:
            - ./config/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped

    portainer:
        image: portainer/portainer-ce:lts
        container_name: portainer
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        restart: unless-stopped
        ports:
            - "3001:3001"
        volumes:
            - uptime-kuma_data:/app/data

    wg-easy:
        image: ghcr.io/wg-easy/wg-easy
        container_name: wg-easy
        environment:
            - PORT=51821
            - WG_PORT=51820
        volumes:
            - wg-easy_data:/etc/wireguard
        ports:
            - "51820:51820/udp"
            - "51821:51821/tcp"
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            net.ipv4.conf.all.src_valid_mark: 1
            net.ipv4.ip_forward: 1
        restart: unless-stopped
        env_file:
            - .env

    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing
        hostname: syncthing
        ports:
            - "8384:8384"
            - "22000:22000/tcp"
            - "22000:22000/udp"
            - "21027:21027/udp"
        volumes:
            - /var/syncthing:/var/syncthing
            - syncthing_data:/var/data
        restart: unless-stopped

volumes:
    portainer_data:
        name: portainer_data
        driver: local
    uptime-kuma_data:
        name: uptime-kuma_data
        driver: local
    wg-easy_data:
        name: wg-easy_data
        driver: local
    syncthing_data:
        name: syncthing_data
        driver: local
