services:
    portainer:
        image: portainer/portainer-ce:lts
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - proxy_network

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        profiles: ["update"]
        networks:
            - proxy_network
        env_file:
            - .env

    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: database
        networks:
            - proxy_network

    tinyfilemanager:
        image: tinyfilemanager/tinyfilemanager:master
        container_name: tinyfilemanager
        restart: unless-stopped
        volumes:
            - /home/${USERNAME}:/var/www/html/data
        networks:
            - proxy_network

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    portainer_data:
        name: portainer_data
        driver: local
    duplicati_data:
        name: duplicati_data
        driver: local
