services:
    wg-easy:
        image: ghcr.io/wg-easy/wg-easy
        container_name: wg-easy
        environment:
            PORT: 51821
        volumes:
            - wg-easy_data:/etc/wireguard
        ports:
            - 51820:51820/udp
            - 51821:51821/tcp
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            net.ipv4.conf.all.src_valid_mark: 1
            net.ipv4.ip_forward: 1
        restart: unless-stopped
        networks:
            - proxy_network
        env_file:
            - .env

    adguard:
        image: adguard/adguardhome
        container_name: adguard
        restart: unless-stopped
        volumes:
            - adguard_data:/opt/adguardhome/work
            - adguard_config:/opt/adguardhome/conf
        networks:
            - proxy_network

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    wg-easy_data:
        name: wg-easy_data
        driver: local
    adguard_data:
        name: adguard_data
        driver: local
    adguard_config:
        name: adguard_config
        driver: local
