services:
    nginx-proxy-manager:
        image: "jc21/nginx-proxy-manager:latest"
        container_name: nginx-proxy-manager
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        networks:
            - proxy_network
            - monitoring
        volumes:
            - ./data/nginx:/data
            - /etc/letsencrypt:/etc/letsencrypt
        environment:
            INITIAL_ADMIN_EMAIL: ${NGINX_PROXY_MANAGER_ADMIN_EMAIL}
            INITIAL_ADMIN_PASSWORD: ${NGINX_PROXY_MANAGER_ADMIN_PASSWORD}
        env_file:
            - .env

    portainer:
        image: portainer/portainer-ce:lts
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        networks:
            - proxy_network

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        profiles: ["update"]
        networks:
            - proxy_network
        env_file:
            - .env

networks:
    proxy_network:
        name: proxy_network
        external: true
    monitoring:
        name: monitoring
        external: true

volumes:
    portainer_data:
        name: portainer_data
        driver: local
    duplicati_data:
        name: duplicati_data
        driver: local
