services:
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        restart: unless-stopped
        volumes:
            - uptime-kuma_data:/app/data
        networks:
            - proxy_network
            - monitoring
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 128M

    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        networks:
            - monitoring
            - proxy_network
        environment:
            GF_SERVER_ROOT_URL: http://grafana.localhost/
            GF_SERVER_SERVE_FROM_SUB_PATH: tru
        restart: unless-stopped
        volumes:
            - grafana_data:/var/lib/grafana
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1024M
        depends_on:
            - prometheus

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        networks:
            - monitoring
            - proxy_network
        volumes:
            - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "2.0"
                    memory: 4096M
                reservations:
                    memory: 512M

    node-exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node-exporter
        networks:
            - monitoring
            - proxy_network
        volumes:
            - /:/host:ro,rslave
        command: --path.rootfs=/host
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 64M

    netdata:
        image: netdata/netdata
        container_name: netdata
        pid: host
        networks:
            - monitoring
            - proxy_network
        volumes:
            - netdataconfig:/etc/netdata
            - netdatalib:/var/lib/netdata
            - netdatacache:/var/cache/netdata
            - /:/host/root:ro,rslave
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /etc/localtime:/etc/localtime:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/log:/host/var/log:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /run/dbus:/run/dbus:ro
        restart: unless-stopped
        cap_add:
            - SYS_PTRACE
            - SYS_ADMIN
        security_opt:
            - apparmor=unconfined

    cadvisor:
        image: gcr.io/cadvisor/cadvisor
        container_name: cadvisor
        privileged: true
        restart: unless-stopped
        networks:
            - monitoring
            - proxy_network
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        devices:
            - /dev/kmsg
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 64M

networks:
    proxy_network:
        name: proxy_network
        external: true
    monitoring:
        name: monitoring
        driver: bridge

volumes:
    uptime-kuma_data:
        name: uptime-kuma_data
        driver: local
    prometheus_data:
        name: prometheus_data
        driver: local
    netdataconfig:
        name: netdataconfig
        driver: local
    netdatalib:
        name: netdatalib
        driver: local
    netdatacache:
        name: netdatacache
        driver: local
    grafana_data:
        name: grafana_data
        driver: local
