services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        volumes:
            - ./data/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 256M

    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing
        hostname: syncthing
        ports:
            - "22000:22000/tcp"
            - "22000:22000/udp"
            - "21027:21027/udp"
        volumes:
            - /var/syncthing:/var/syncthing
            - syncthing_data:/var/data
        restart: unless-stopped
        networks:
            - proxy_network

    vaultwarden:
        image: vaultwarden/server:latest
        container_name: vaultwarden
        volumes:
            - vaultwarden_data:/data/
        restart: unless-stopped
        environment:
            - ROCKET_WEB_VAULT_PREFIX=/vaultwarden
        networks:
            - proxy_network

    tinyfilemanager:
        image: tinyfilemanager/tinyfilemanager:master
        container_name: tinyfilemanager
        restart: unless-stopped
        volumes:
            - /home/${USERNAME}:/var/www/html/data
        networks:
            - proxy_network

    database:
        image: mariadb:11
        container_name: database
        restart: unless-stopped
        stop_grace_period: 5s
        command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
        volumes:
            - "database_data:/var/lib/mysql"
        environment:
            MARIADB_AUTO_UPGRADE: "1"
            MARIADB_INITDB_SKIP_TZINFO: "1"
            MARIADB_ROOT_PASSWORD: "insecure"
        env_file:
            - .env
        networks:
            - proxy_network

networks:
    proxy_network:
        name: proxy_network
        driver: bridge

volumes:
    syncthing_data:
        name: syncthing_data
        driver: local
    vaultwarden_data:
        name: vaultwarden_data
        driver: local
    database_data:
        name: database_data
        driver: local
