services:
    nginx-proxy-manager:
        image: jc21/nginx-proxy-manager:latest
        container_name: nginx-proxy-manager
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
            - 81:81
        networks:
            - proxy_network
        volumes:
            - nginx-proxy-manager_data:/data
            - /etc/letsencrypt:/etc/letsencrypt
        environment:
            INITIAL_ADMIN_EMAIL: ${NGINX_PROXY_MANAGER_ADMIN_EMAIL}
            INITIAL_ADMIN_PASSWORD: ${NGINX_PROXY_MANAGER_ADMIN_PASSWORD}
            DB_MYSQL_HOST: database
            DB_MYSQL_PORT: 3306
            DB_MYSQL_USER: ${NGINX_PROXY_MANAGER_DATABASE_USER}
            DB_MYSQL_PASSWORD: ${NGINX_PROXY_MANAGER_DATABASE_PASSWORD}
            DB_MYSQL_NAME: ${NGINX_PROXY_MANAGER_DATABASE_NAME}
        env_file:
            - .env

    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        volumes:
            - ./data/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 256M

    database:
        image: mariadb:11
        container_name: database
        restart: unless-stopped
        stop_grace_period: 5s
        command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
        volumes:
            - database_data:/var/lib/mysql
            - ./data/database:/docker-entrypoint-initdb.d
        environment:
            MARIADB_AUTO_UPGRADE: 1
            MARIADB_INITDB_SKIP_TZINFO: 1
            MARIADB_ROOT_PASSWORD: insecure
        env_file:
            - .env
        networks:
            - proxy_network
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

networks:
    proxy_network:
        name: proxy_network
        driver: bridge

volumes:
    database_data:
        name: database_data
        driver: local
    nginx-proxy-manager_data:
        name: nginx-proxy-manager_data
        driver: local
