services:
    photoprism:
        image: photoprism/photoprism:latest
        container_name: photoprism
        restart: unless-stopped
        environment:
            PHOTOPRISM_AUTH_MODE: password
            PHOTOPRISM_SITE_URL: http://prism.localhost/
            PHOTOPRISM_DATABASE_DRIVER: mysql
            PHOTOPRISM_DATABASE_SERVER: database:3306
            PHOTOPRISM_SITE_CAPTION: Photoprism
            PHOTOPRISM_SITE_DESCRIPTION: "Self-hosted photo and video organizer."
        volumes:
            - /var/photos:/photoprism/originals
            - photoprism_data:/photoprism/storage
        networks:
            - proxy_network
        env_file:
            - .env

    navidrome:
        image: deluan/navidrome:latest
        container_name: navidrome
        restart: unless-stopped
        volumes:
            - navidrome_data:/data
            - /var/music:/music:ro
        networks:
            - proxy_network
        environment:
            ND_PROMETHEUS_ENABLED: true
            ND_PROMETHEUS_METRICSPATH: /metrics
        env_file:
            - .env

    kavita:
        image: jvmilazz0/kavita:latest
        container_name: kavita
        volumes:
            - /var/data/comics:/comics
            - /var/data/books:/books
            - /var/data/manga:/manga
            - kavita_data:/kavita/config
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    cpus: "0.75"
                    memory: 768M

    mealie:
        image: ghcr.io/mealie-recipes/mealie:v2.6.0
        container_name: mealie
        restart: unless-stopped
        volumes:
            - mealie_data:/app/data/
        environment:
            ALLOW_SIGNUP: ${MEALIE_ALLOW_SIGNUP}
            MAX_WORKERS: ${MEALIE_MAX_WORKERS}
            WEB_CONCURRENCY: ${MEALIE_WEB_CONCURRENCY}
            SECURITY_MAX_LOGIN_ATTEMPTS: ${MEALIE_SECURITY_MAX_LOGIN_ATTEMPTS}
            SECURITY_USER_LOCKOUT_TIME: ${MEALIE_SECURITY_USER_LOCKOUT_TIME}
        env_file:
            - .env
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    memory: 1000M

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    kavita_data:
        name: kavita_data
        driver: local
    navidrome_data:
        name: navidrome_data
        driver: local
    photoprism_data:
        name: photoprism_data
        driver: local
    mealie_data:
        name: mealie_data
        driver: local
