services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        volumes:
            - ./data/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 256M

    tinyfilemanager:
        image: tinyfilemanager/tinyfilemanager:master
        container_name: tinyfilemanager
        restart: unless-stopped
        volumes:
            - /home/${USERNAME}:/var/www/html/data
        networks:
            - proxy_network

    database:
        image: mariadb:11
        container_name: database
        restart: unless-stopped
        stop_grace_period: 5s
        command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
        volumes:
            - "database_data:/var/lib/mysql"
        environment:
            MARIADB_AUTO_UPGRADE: "1"
            MARIADB_INITDB_SKIP_TZINFO: "1"
            MARIADB_ROOT_PASSWORD: "insecure"
        env_file:
            - .env
        networks:
            - proxy_network

networks:
    proxy_network:
        name: proxy_network
        driver: bridge

volumes:
    database_data:
        name: database_data
        driver: local
