services:
    photoprism:
        image: photoprism/photoprism:latest
        container_name: photoprism
        restart: unless-stopped
        environment:
            PHOTOPRISM_ADMIN_USER: "admin"
            PHOTOPRISM_ADMIN_PASSWORD: "strongpassword"
            PHOTOPRISM_AUTH_MODE: "password"
            PHOTOPRISM_SITE_URL: "http://prism.localhost/"
            PHOTOPRISM_BACKUP_ALBUMS: true
            PHOTOPRISM_BACKUP_DATABASE: true
            PHOTOPRISM_BACKUP_SCHEDULE: "daily"
            PHOTOPRISM_DATABASE_DRIVER: "mysql"
            PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
            PHOTOPRISM_DATABASE_NAME: "${MARIADB_DATABASE:-photoprism}"
            PHOTOPRISM_DATABASE_USER: "${MARIADB_USER:-photoprism}"
            PHOTOPRISM_DATABASE_PASSWORD: "${MARIADB_PASSWORD:-insecure}"
        volumes:
            - /var/photos:/photoprism/originals
            - photoprism_data:/photoprism/storage
        depends_on:
            - mariadb
        networks:
            - proxy_network
        env_file:
            - .env

    navidrome:
        image: deluan/navidrome:latest
        container_name: navidrome
        restart: unless-stopped
        volumes:
            - "navidrome_data:/data"
            - "/var/music:/music:ro"
        networks:
            - proxy_network
        environment:
            ND_SCANSCHEDULE: "@every 1h"
            ND_LOGLEVEL: "info"
            ND_UIWELCOMEMESSAGE: "Welcome Back!"
            ND_DEFAULTTHEME: "Dark"
            ND_ENABLECOVERANIMATION: "true"
            ND_ENABLEDOWNLOADS: "true"
            ND_SESSIONTIMEOUT: "24h"
        env_file:
            - .env

    kavita:
        image: jvmilazz0/kavita:latest
        container_name: kavita
        volumes:
            - /var/data/comics:/comics
            - /var/data/books:/books
            - /var/data/manga:/manga
            - kavita_data:/kavita/config
        restart: unless-stopped
        env_file:
            - .env
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    cpus: "0.75"
                    memory: 768M

    mealie:
        image: ghcr.io/mealie-recipes/mealie:v2.6.0
        container_name: mealie
        restart: unless-stopped
        volumes:
            - mealie_data:/app/data/
        environment:
            ALLOW_SIGNUP: false
            PUID: 1000
            PGID: 1000
            MAX_WORKERS: 2
            WEB_CONCURRENCY: 1
            SECURITY_MAX_LOGIN_ATTEMPTS: 5
            SECURITY_USER_LOCKOUT_TIME: 1
        env_file:
            - .env
        networks:
            - proxy_network
        deploy:
            resources:
                limits:
                    memory: 1000M

volumes:
    kavita_data:
        name: kavita_data
        driver: local
    navidrome_data:
        name: navidrome_data
        driver: local
    photoprism_data:
        name: photoprism_data
        driver: local
    mealie_data:
        name: mealie_data
        driver: local
