services:
    myspeed:
        container_name: myspeed
        image: "germannewsmaker/myspeed"
        restart: unless-stopped
        volumes:
            - myspeed_data:/myspeed/data
        networks:
            - proxy_network

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    myspeed_data:
        name: myspeed_data
        driver: local
