---
name: self-hosted

services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    restart: unless-stopped
    volumes:
      - myspeed_data:/myspeed/data

volumes:
  myspeed_data:
    name: myspeed_data
    driver: local
