name: self-hosted

services:
    myspeed:
        container_name: myspeed
        image: "germannewsmaker/myspeed"
        restart: unless-stopped
        volumes:
            - myspeed_data:/myspeed/data

volumes:
    myspeed_data:
        name: myspeed_data
        driver: local
