- Developer:
      - GitHub:
            - abbr: GH
              href: https://github.com/vix-4800
      - GitLab:
            - abbr: GL
              href: https://gitlab.com/vix-4800

- Social:
      - Telegram:
            - abbr: TG
              href: https://t.me/vix_4800
