- Infrastructure:
      - Portainer:
            icon: portainer.png
            href: http://localhost:9000/#!/home
            description: "Management of Docker containers"
      - Watchtower:
            icon: watchtower.png
            description: Auto-update containers

- Monitoring:
      - Netdata:
            icon: netdata.png
            href: http://localhost:19999
            description: "Server resource monitoring"
      - Grafana:
            icon: grafana.png
            href: http://localhost:3000
            description: "Monitoring of servers"
      - Node Exporter:
            icon: prometheus.png
            description: Hardware metrics
      - Prometheus:
            icon: prometheus.png
            href: http://localhost:9090
            description: Time-series database
      - "Uptime Kuma":
            icon: uptime-kuma.png
            href: http://localhost:3001/dashboard
            description: "Availability monitoring"

- Media:
      - Syncthing:
            icon: syncthing.png
            href: http://localhost:8384
            description: "File synchronization"
      - Mealie:
            icon: mealie.png
            href: http://localhost:9925
            description: "Recipe management"

- Network:
      - WireGuard:
            icon: wireguard.png
            href: http://localhost:51821/
            description: "VPN server"
      - Pi-hole:
            icon: pihole.png
            href: https://pihole.example.com
            description: "Ad blocking"

- Security:
      - Vaultwarden:
            icon: vaultwarden.png
            href: http://localhost:8080
            description: "Password manager"
