name: self-hosted

services:
    n8n:
        image: docker.n8n.io/n8nio/n8n
        container_name: n8n
        stdin_open: true
        tty: true
        ports:
            - 5678:5678
        volumes:
            - n8n_data:/home/node/.n8n

volumes:
    n8n_data:
        name: n8n_data
        driver: local
