name: self-hosted

services:
    gitea:
        image: docker.io/gitea/gitea:nightly
        container_name: gitea
        environment:
            USER_UID: ${PUID}
            USER_GID: ${PGID}
            GITEA__database__DB_TYPE: mysql
            GITEA__database__HOST: database:3306
            GITEA__database__NAME: ${GITEA_DATABASE_NAME}
            GITEA__database__USER: ${GITEA_DATABASE_USER}
            GITEA__database__PASSWD: ${GITEA_DATABASE_PASSWORD}
            GITEA__mailer__ENABLED: true
            GITEA__mailer__PROTOCOL: smtps
        restart: unless-stopped
        volumes:
            - gitea_data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - ../.env

volumes:
    gitea_data:
        name: gitea_data
        driver: local
