name: self-hosted

services:
    gotify:
        image: gotify/server
        container_name: gotify
        volumes:
            - gotify_data:/app/data
        env_file:
            - ../.env

volumes:
    gotify_data:
        name: gotify_data
        driver: local
