name: self-hosted

services:
    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        networks:
            - proxy_network
        environment:
            GF_SERVER_ROOT_URL: http://grafana.localhost/
            GF_SERVER_SERVE_FROM_SUB_PATH: tru
        restart: unless-stopped
        volumes:
            - grafana_data:/var/lib/grafana
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1024M

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    grafana_data:
        name: grafana_data
        driver: local
