---
services:
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    container_name: immich_machine_learning
    extends:
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - model-cache:/cache
    restart: unless-stopped
    ports:
      - 3003:3003

volumes:
  model-cache:
