name: self-hosted

services:
    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        volumes:
            - ./config:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        env_file:
            - ../.env
        deploy:
            resources:
                limits:
                    cpus: "0.50"
                    memory: 256M
