services:
    database:
        image: mariadb:11
        container_name: database
        restart: unless-stopped
        stop_grace_period: 5s
        command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
        volumes:
            - database_data:/var/lib/mysql
            - ./entrypoint:/docker-entrypoint-initdb.d
        environment:
            MARIADB_AUTO_UPGRADE: 1
            MARIADB_INITDB_SKIP_TZINFO: 1
            MARIADB_ROOT_PASSWORD: insecure
        env_file:
            - ../.env
        networks:
            - proxy_network
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    database_data:
        name: database_data
        driver: local
