services:
    tinyfilemanager:
        image: tinyfilemanager/tinyfilemanager:master
        container_name: tinyfilemanager
        restart: unless-stopped
        volumes:
            - /home/${USERNAME}:/var/www/html/data
        networks:
            - proxy_network

networks:
    proxy_network:
        name: proxy_network
        external: true
