services:
    adminer:
        image: adminer
        container_name: adminer
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: database
        networks:
            - proxy_network

networks:
    proxy_network:
        name: proxy_network
        external: true
