name: self-hosted

services:
    kimai-db:
        image: mysql:8.3
        container_name: kimai-db
        restart: unless-stopped
        volumes:
            - kimai_mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${KIMAI_DATABASE}
            MYSQL_USER: ${KIMAI_USER}
            MYSQL_PASSWORD: ${KIMAI_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${KIMAI_ROOT_PASSWORD}
        command: --default-storage-engine innodb
        env_file:
            - ../.env
        healthcheck:
            test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
            interval: 20s
            start_period: 10s
            timeout: 10s
            retries: 3

    kimai:
        image: kimai/kimai2:apache
        container_name: kimai
        restart: unless-stopped
        volumes:
            - kimai_data:/opt/kimai/var/data
            - kimai_plugins:/opt/kimai/var/plugins
        ports:
            - 8001:8001
        env_file:
            - ../.env
        environment:
            ADMINMAIL: ${KIMAI_ADMIN_MAIL}
            ADMINPASS: ${KIMAI_ADMIN_PASS}
            DATABASE_URL: ${KIMAI_DATABASE_URL}

volumes:
    kimai_data:
        name: kimai_data
        driver: local
    kimai_mysql:
        name: kimai_mysql
        driver: local
    kimai_plugins:
        name: kimai_plugins
        driver: local
