name: self-hosted

services:
    portainer:
        image: portainer/portainer-ce:lts
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

volumes:
    portainer_data:
        name: portainer_data
        driver: local
