name: self-hosted

services:
    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing
        hostname: syncthing
        network_mode: host
        volumes:
            - syncthing_data:/var/syncthing # configs
            # - ...:/var/syncthing/... # data
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Moscow
        healthcheck:
            test: curl -fkLsS -m 2 localhost:8384/rest/noauth/health | grep -o --color=never OK || exit 1
            interval: 1m
            timeout: 10s
            retries: 3

volumes:
    syncthing_data:
        name: syncthing_data
        driver: local
