services:
    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing
        hostname: syncthing
        ports:
            - 22000:22000/tcp
            - 22000:22000/udp
            - 21027:21027/udp
        volumes:
            - /var/syncthing:/var/syncthing
            - syncthing_data:/var/data
        restart: unless-stopped
        networks:
            - proxy_network
        healthcheck:
            test: curl -fkLsS -m 2 localhost:8384/rest/noauth/health | grep -o --color=never OK || exit 1
            interval: 1m
            timeout: 10s
            retries: 3

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    syncthing_data:
        name: syncthing_data
        driver: local
