services:
    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing
        hostname: syncthing
        ports:
            - 8384:8384
            - 22000:22000/tcp
            - 22000:22000/udp
            - 21027:21027/udp
        volumes:
            - syncthing_data:/var/data
            - /sync:/var/syncthing
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Moscow
        healthcheck:
            test: curl -fkLsS -m 2 localhost:8384/rest/noauth/health | grep -o --color=never OK || exit 1
            interval: 1m
            timeout: 10s
            retries: 3

volumes:
    syncthing_data:
        name: syncthing_data
        driver: local
