name: self-hosted

services:
    app:
        image: fireflyiii/core:latest
        container_name: firefly_iii_core
        hostname: app
        restart: unless-stopped
        volumes:
            - firefly_iii_upload:/var/www/html/storage/upload
        env_file:
            - ../.env
        environment:
            DB_PASSWORD: ${FIREFLY_DB_PASSWORD}
        networks:
            - firefly_iii
        ports:
            - 80:8080
        depends_on:
            - db

    db:
        image: mariadb:lts
        container_name: firefly_iii_db
        hostname: db
        restart: unless-stopped
        env_file:
            - ../.env
        environment:
            MYSQL_PASSWORD: ${FIREFLY_MYSQL_PASSWORD}
        networks:
            - firefly_iii
        volumes:
            - firefly_iii_db:/var/lib/mysql

    cron:
        #
        # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace PLEASE_REPLACE_WITH_32_CHAR_CODE below
        # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
        #
        image: alpine
        container_name: firefly_iii_cron
        restart: unless-stopped
        env_file:
            - ../.env
        environment:
            DB_PASSWORD: ${FIREFLY_DB_PASSWORD}
        command: sh -c "
            apk add tzdata
            && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
            | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/PLEASE_REPLACE_WITH_32_CHAR_CODE;echo\"
            | crontab -
            && crond -f -L /dev/stdout"
        networks:
            - firefly_iii

volumes:
    firefly_iii_upload:
        name: firefly_iii_upload
        driver: local
    firefly_iii_db:
        name: firefly_iii_db
        driver: local

networks:
    firefly_iii:
        driver: bridge
