services:
    redis:
        image: redis:alpine
        restart: unless-stopped
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - proxy_network
        volumes:
            - redis_data:/data
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

networks:
    proxy_network:
        name: proxy_network
        external: true

volumes:
    redis_data:
        name: redis_data
        driver: local
