name: self-hosted

services:
    redis:
        image: redis:alpine
        restart: unless-stopped
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

volumes:
    redis_data:
        name: redis_data
        driver: local
